version: "3"
services: 
  elasticsearch: 
    image: elasticsearch:7.8.1
    ports: 
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
  kibana:
    image: kibana:7.8.1
    ports: 
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on: 
      - elasticsearch